# Numpy and Scipy
## Today in class we'll cover scalars, arrays, tensors, matrices, and some basic programming stuff.

First let's learn some commands

* `Shift + Enter` run the current cell, select below
* `Ctrl + Enter` run selected cells
* `Alt + Enter` run the current cell, insert below
* `Ctrl + S` save and checkpoint

If you're using a mac:
* Ctrl = command key ⌘
* Shift  = Shift ⇧
* Alt  = option ⌥

I got these from here where there are more commands hints etc.:
https://towardsdatascience.com/jypyter-notebook-shortcuts-bf0101a98330

# Saving
For today it won't be an issue, but remember that everytime you save this document and if it perhaps differs from what's on github, the next time you run `git pull` you'll overwrite your local files in the adv_cognitive_neuroscience directory.  That is why I highly recommend making your own branch (or fork) or figuring out a way to not overwrite future file.

But for today I don't imagine you'll make too many personal edits to this file in need of preserving.

# Basic notebook stuff
## let's start with the shift + enter command

In [4]:
# this is the first cell that we'll actually execute
print('welcome to week 1')

welcome to week 1


In [5]:
# The idea here is that we can put a portion or snippet of code into one of these cells
# and immediately see its output.  This helps keep science and code tidy while also
# making code readable to others.
for i in range(12):
    textToPrint = "welcome to week " + str(i)
    print(textToPrint)


welcome to week 0
welcome to week 1
welcome to week 2
welcome to week 3
welcome to week 4
welcome to week 5
welcome to week 6
welcome to week 7
welcome to week 8
welcome to week 9
welcome to week 10
welcome to week 11


# Libaries
The code that we've run so far (i.e., `print` `for` `range`) all relies on built-in functions that come stock with python installs. Families of functions that aren't prepackaged with python do exist, are immensely useful, and are typically released as a library.

When we created the environment acn we automated the installation of a lot of libraries that contain functions necessary for what we want to do to data.  Two bedrock libraries for almost anybody working with data are numpy and scipy and the way that you let python know that you want to use their functions in the code you're writing is with the following syntax:

><p>import numpy as np</p>
import scipy as sp

In the next cell is a little example of some of the commands that are within numpy

In [ ]:
import numpy as np # here we tell python will be using numpy's functions abrv as np
a = np.arange(15).reshape(3, 5) # here we ask np to make a range (0-14) with a shape
a # display the matrix

# Scalars
## Scalars can seem a bit complex at first 
Look at this this table is from the numpy website:
<p>Booleans:</p>
<table class="docutils align-default">
<colgroup>
<col style="width: 30%" />
<col style="width: 46%" />
<col style="width: 24%" />
</colgroup>
<thead>
<tr class="row-odd"><th class="head"><p>Type</p></th>
<th class="head"><p>Remarks</p></th>
<th class="head"><p>Character code</p></th>
</tr>
</thead>
<tbody>
<tr class="row-even"><td><p><code class="xref py py-class docutils literal notranslate"><span class="pre">bool_</span></code></p></td>
<td><p>compatible: Python bool</p></td>
<td><p><code class="docutils literal notranslate"><span class="pre">'?'</span></code></p></td>
</tr>
<tr class="row-odd"><td><p><code class="xref py py-class docutils literal notranslate"><span class="pre">bool8</span></code></p></td>
<td><p>8 bits</p></td>
<td></td>
</tr>
</tbody>
</table>
<p>Integers:</p>
<table class="docutils align-default">
<colgroup>
<col style="width: 30%" />
<col style="width: 46%" />
<col style="width: 24%" />
</colgroup>
<tbody>
<tr class="row-odd"><td><p><code class="xref py py-class docutils literal notranslate"><span class="pre">byte</span></code></p></td>
<td><p>compatible: C char</p></td>
<td><p><code class="docutils literal notranslate"><span class="pre">'b'</span></code></p></td>
</tr>
<tr class="row-even"><td><p><code class="xref py py-class docutils literal notranslate"><span class="pre">short</span></code></p></td>
<td><p>compatible: C short</p></td>
<td><p><code class="docutils literal notranslate"><span class="pre">'h'</span></code></p></td>
</tr>
<tr class="row-odd"><td><p><code class="xref py py-class docutils literal notranslate"><span class="pre">intc</span></code></p></td>
<td><p>compatible: C int</p></td>
<td><p><code class="docutils literal notranslate"><span class="pre">'i'</span></code></p></td>
</tr>
<tr class="row-even"><td><p><code class="xref py py-class docutils literal notranslate"><span class="pre">int_</span></code></p></td>
<td><p>compatible: Python int</p></td>
<td><p><code class="docutils literal notranslate"><span class="pre">'l'</span></code></p></td>
</tr>
<tr class="row-odd"><td><p><code class="xref py py-class docutils literal notranslate"><span class="pre">longlong</span></code></p></td>
<td><p>compatible: C long long</p></td>
<td><p><code class="docutils literal notranslate"><span class="pre">'q'</span></code></p></td>
</tr>
<tr class="row-even"><td><p><code class="xref py py-class docutils literal notranslate"><span class="pre">intp</span></code></p></td>
<td><p>large enough to fit a pointer</p></td>
<td><p><code class="docutils literal notranslate"><span class="pre">'p'</span></code></p></td>
</tr>
<tr class="row-odd"><td><p><code class="xref py py-class docutils literal notranslate"><span class="pre">int8</span></code></p></td>
<td><p>8 bits</p></td>
<td></td>
</tr>
<tr class="row-even"><td><p><code class="xref py py-class docutils literal notranslate"><span class="pre">int16</span></code></p></td>
<td><p>16 bits</p></td>
<td></td>
</tr>
<tr class="row-odd"><td><p><code class="xref py py-class docutils literal notranslate"><span class="pre">int32</span></code></p></td>
<td><p>32 bits</p></td>
<td></td>
</tr>
<tr class="row-even"><td><p><code class="xref py py-class docutils literal notranslate"><span class="pre">int64</span></code></p></td>
<td><p>64 bits</p></td>
<td></td>
</tr>
</tbody>
</table>
<p>Unsigned integers:</p>
<table class="docutils align-default">
<colgroup>
<col style="width: 30%" />
<col style="width: 46%" />
<col style="width: 24%" />
</colgroup>
<tbody>
<tr class="row-odd"><td><p><code class="xref py py-class docutils literal notranslate"><span class="pre">ubyte</span></code></p></td>
<td><p>compatible: C unsigned char</p></td>
<td><p><code class="docutils literal notranslate"><span class="pre">'B'</span></code></p></td>
</tr>
<tr class="row-even"><td><p><code class="xref py py-class docutils literal notranslate"><span class="pre">ushort</span></code></p></td>
<td><p>compatible: C unsigned short</p></td>
<td><p><code class="docutils literal notranslate"><span class="pre">'H'</span></code></p></td>
</tr>
<tr class="row-odd"><td><p><code class="xref py py-class docutils literal notranslate"><span class="pre">uintc</span></code></p></td>
<td><p>compatible: C unsigned int</p></td>
<td><p><code class="docutils literal notranslate"><span class="pre">'I'</span></code></p></td>
</tr>
<tr class="row-even"><td><p><code class="xref py py-class docutils literal notranslate"><span class="pre">uint</span></code></p></td>
<td><p>compatible: Python int</p></td>
<td><p><code class="docutils literal notranslate"><span class="pre">'L'</span></code></p></td>
</tr>
<tr class="row-odd"><td><p><code class="xref py py-class docutils literal notranslate"><span class="pre">ulonglong</span></code></p></td>
<td><p>compatible: C long long</p></td>
<td><p><code class="docutils literal notranslate"><span class="pre">'Q'</span></code></p></td>
</tr>
<tr class="row-even"><td><p><code class="xref py py-class docutils literal notranslate"><span class="pre">uintp</span></code></p></td>
<td><p>large enough to fit a pointer</p></td>
<td><p><code class="docutils literal notranslate"><span class="pre">'P'</span></code></p></td>
</tr>
<tr class="row-odd"><td><p><code class="xref py py-class docutils literal notranslate"><span class="pre">uint8</span></code></p></td>
<td><p>8 bits</p></td>
<td></td>
</tr>
<tr class="row-even"><td><p><code class="xref py py-class docutils literal notranslate"><span class="pre">uint16</span></code></p></td>
<td><p>16 bits</p></td>
<td></td>
</tr>
<tr class="row-odd"><td><p><code class="xref py py-class docutils literal notranslate"><span class="pre">uint32</span></code></p></td>
<td><p>32 bits</p></td>
<td></td>
</tr>
<tr class="row-even"><td><p><code class="xref py py-class docutils literal notranslate"><span class="pre">uint64</span></code></p></td>
<td><p>64 bits</p></td>
<td></td>
</tr>
</tbody>
</table>
<p>Floating-point numbers:</p>
<table class="docutils align-default">
<colgroup>
<col style="width: 30%" />
<col style="width: 46%" />
<col style="width: 24%" />
</colgroup>
<tbody>
<tr class="row-odd"><td><p><code class="xref py py-class docutils literal notranslate"><span class="pre">half</span></code></p></td>
<td></td>
<td><p><code class="docutils literal notranslate"><span class="pre">'e'</span></code></p></td>
</tr>
<tr class="row-even"><td><p><code class="xref py py-class docutils literal notranslate"><span class="pre">single</span></code></p></td>
<td><p>compatible: C float</p></td>
<td><p><code class="docutils literal notranslate"><span class="pre">'f'</span></code></p></td>
</tr>
<tr class="row-odd"><td><p><code class="xref py py-class docutils literal notranslate"><span class="pre">double</span></code></p></td>
<td><p>compatible: C double</p></td>
<td></td>
</tr>
<tr class="row-even"><td><p><code class="xref py py-class docutils literal notranslate"><span class="pre">float_</span></code></p></td>
<td><p>compatible: Python float</p></td>
<td><p><code class="docutils literal notranslate"><span class="pre">'d'</span></code></p></td>
</tr>
<tr class="row-odd"><td><p><code class="xref py py-class docutils literal notranslate"><span class="pre">longfloat</span></code></p></td>
<td><p>compatible: C long float</p></td>
<td><p><code class="docutils literal notranslate"><span class="pre">'g'</span></code></p></td>
</tr>
<tr class="row-even"><td><p><code class="xref py py-class docutils literal notranslate"><span class="pre">float16</span></code></p></td>
<td><p>16 bits</p></td>
<td></td>
</tr>
<tr class="row-odd"><td><p><code class="xref py py-class docutils literal notranslate"><span class="pre">float32</span></code></p></td>
<td><p>32 bits</p></td>
<td></td>
</tr>
<tr class="row-even"><td><p><code class="xref py py-class docutils literal notranslate"><span class="pre">float64</span></code></p></td>
<td><p>64 bits</p></td>
<td></td>
</tr>
<tr class="row-odd"><td><p><code class="xref py py-class docutils literal notranslate"><span class="pre">float96</span></code></p></td>
<td><p>96 bits, platform?</p></td>
<td></td>
</tr>
<tr class="row-even"><td><p><code class="xref py py-class docutils literal notranslate"><span class="pre">float128</span></code></p></td>
<td><p>128 bits, platform?</p></td>
<td></td>
</tr>
</tbody>
</table>
<p>Complex floating-point numbers:</p>
<table class="docutils align-default">
<colgroup>
<col style="width: 30%" />
<col style="width: 46%" />
<col style="width: 24%" />
</colgroup>
<tbody>
<tr class="row-odd"><td><p><code class="xref py py-class docutils literal notranslate"><span class="pre">csingle</span></code></p></td>
<td></td>
<td><p><code class="docutils literal notranslate"><span class="pre">'F'</span></code></p></td>
</tr>
<tr class="row-even"><td><p><code class="xref py py-class docutils literal notranslate"><span class="pre">complex_</span></code></p></td>
<td><p>compatible: Python complex</p></td>
<td><p><code class="docutils literal notranslate"><span class="pre">'D'</span></code></p></td>
</tr>
<tr class="row-odd"><td><p><code class="xref py py-class docutils literal notranslate"><span class="pre">clongfloat</span></code></p></td>
<td></td>
<td><p><code class="docutils literal notranslate"><span class="pre">'G'</span></code></p></td>
</tr>
<tr class="row-even"><td><p><code class="xref py py-class docutils literal notranslate"><span class="pre">complex64</span></code></p></td>
<td><p>two 32-bit floats</p></td>
<td></td>
</tr>
<tr class="row-odd"><td><p><code class="xref py py-class docutils literal notranslate"><span class="pre">complex128</span></code></p></td>
<td><p>two 64-bit floats</p></td>
<td></td>
</tr>
<tr class="row-even"><td><p><code class="xref py py-class docutils literal notranslate"><span class="pre">complex192</span></code></p></td>
<td><p>two 96-bit floats,
platform?</p></td>
<td></td>
</tr>
<tr class="row-odd"><td><p><code class="xref py py-class docutils literal notranslate"><span class="pre">complex256</span></code></p></td>
<td><p>two 128-bit floats,
platform?</p></td>
<td></td>
</tr>
</tbody>
</table>
<p>Any Python object:</p>
<table class="docutils align-default">
<colgroup>
<col style="width: 30%" />
<col style="width: 46%" />
<col style="width: 24%" />
</colgroup>
<tbody>
<tr class="row-odd"><td><p><code class="xref py py-class docutils literal notranslate"><span class="pre">object_</span></code></p></td>
<td><p>any Python object</p></td>
<td><p><code class="docutils literal notranslate"><span class="pre">'O'</span></code></p></td>
</tr>
</tbody>
</table>

## But don't worry it's not that bad
### Let's start with Arrays
An array is a central data structure of the NumPy library. An array is a grid of values and it contains information about the raw data, how to locate an element, and how to interpret an element. It has a grid of elements that can be indexed in various ways. The elements are all of the same type, referred to as the array dtype.

An array can be indexed by a tuple of nonnegative integers, by booleans, by another array, or by integers. The rank of the array is the number of dimensions. The shape of the array is a tuple of integers giving the size of the array along each dimension.

We mainly work with regular numbers like integers, so let's mess around with some basic examples and see what shakes out.

https://numpy.org/doc/stable/user/absolute_beginners.html

In [8]:
# finish this code 
import numpy as np
x = 20
y = 40
b = np.arange(x,y,2) # make a 1x11 array from 20 to 40
print(b.size) # show the size
print(b) # show what's inside
b = b.reshape(5,2) # change the dimensions to 2 x 5
b # tell be the difference between print(b) and just 'b'

10
[20 22 24 26 28 30 32 34 36 38]


array([[20, 22],
       [24, 26],
       [28, 30],
       [32, 34],
       [36, 38]])

In [9]:
# fun with commands
a.shape

NameError: name 'a' is not defined

In [11]:
b.ndim

1

In [12]:
b.dtype.name

'int64'

In [14]:
b.itemsize

8

In [15]:
b.size

4

In [16]:
type(b)

numpy.ndarray

In [ ]:
b = np.array([6, 7, 8])
b

In [ ]:
type(b)

In [19]:
# Arithmetic operators on arrays apply elementwise.
# A new array is created and filled with the result
a = np.array([20, 30, 40, 50]) #another way of specifying an array. 
b = np.arange(4) #4 elements starting from zero and going up. 
print(a)
print(b)

[20 30 40 50]
[0 1 2 3]


In [20]:
c = a-b # simple
c

array([20, 29, 38, 47])

In [21]:
b**2 # what does the double ** do?

array([0, 1, 4, 9])

In [22]:
10*np.sin(a) # another neat function of numpy np.sin()

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [29]:
a<35 # boolean values (but why)?

array([ True,  True, False, False])

In [43]:
from numpy import pi
np.linspace( 0, 2, 9 )                 # 9 numbers from 0 to 2
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [44]:
x = np.linspace( 0, 2*pi, 100 )        # useful to evaluate function at lots of points
print(x)

[0.         0.06346652 0.12693304 0.19039955 0.25386607 0.31733259
 0.38079911 0.44426563 0.50773215 0.57119866 0.63466518 0.6981317
 0.76159822 0.82506474 0.88853126 0.95199777 1.01546429 1.07893081
 1.14239733 1.20586385 1.26933037 1.33279688 1.3962634  1.45972992
 1.52319644 1.58666296 1.65012947 1.71359599 1.77706251 1.84052903
 1.90399555 1.96746207 2.03092858 2.0943951  2.15786162 2.22132814
 2.28479466 2.34826118 2.41172769 2.47519421 2.53866073 2.60212725
 2.66559377 2.72906028 2.7925268  2.85599332 2.91945984 2.98292636
 3.04639288 3.10985939 3.17332591 3.23679243 3.30025895 3.36372547
 3.42719199 3.4906585  3.55412502 3.61759154 3.68105806 3.74452458
 3.8079911  3.87145761 3.93492413 3.99839065 4.06185717 4.12532369
 4.1887902  4.25225672 4.31572324 4.37918976 4.44265628 4.5061228
 4.56958931 4.63305583 4.69652235 4.75998887 4.82345539 4.88692191
 4.95038842 5.01385494 5.07732146 5.14078798 5.2042545  5.26772102
 5.33118753 5.39465405 5.45812057 5.52158709 5.58505361 5.648520

# Indexing & Slicing
## Sometimes we need to pull out certain elements of an array
This is called indexing and is very helpful when working with big data sets and time series types of data.  Remember that python uses 0 indexing so the first element of any array or matrix is referred to as the 0 element.

[id]: https://numpy.org/doc/stable/_images/np_indexing.png

![Alt text][id]

In [77]:
# let's do some indexing
a = np.arange(10)**3
print(a) # remember the double **?
print(a[-1:])
print(a[-2:])

[  0   1   8  27  64 125 216 343 512 729]
[729]
[512 729]


In [65]:
# only pull out the number 8 from array a, remember 0 indexing!
x = 2
print(a[x]) 

8


In [66]:
# pull out only [8 27 64]
y = 5
x = 2
print(a[x:y])
print(a)

[ 8 27 64]
[  0   1   8  27  64 125 216 343 512 729]


In [81]:
# change every other element to 1000 from index 0 to 6
y = 6 
z = 2 #every other..
a[:y:z] = 1000 # same as a[0:y:z] 
print(a)

#getting size: 
print(f"using np.size(): {np.size(a)}")
print(f"using just len: {len(a)}")

[1000    1 1000   27 1000  125  216  343  512  729]
using np.size(): 10
using just len: 10


In [68]:
# a is now reversed
print(a[ : :-1]) 

[ 729  512  343  216  125 1000   27 1000    1 1000]


In [82]:
# Get loopy with it.  Tell me what i is on each loop
for i in a:
    print(i**(1/3))

9.999999999999998
1.0
9.999999999999998
3.0
9.999999999999998
4.999999999999999
5.999999999999999
6.999999999999999
7.999999999999999
8.999999999999998


In [86]:
## testing some of the printing arrays stuff (below): 
b = np.array( [ [1, 0], [6, 4] ] )
print(b)

[[1 0]
 [6 4]]


In [94]:
## how to trouble-shoot ## 
#np.linspace? #getting docstirng and documentation
#np.linspace?? #getting source code. 

# Some notes on Arrays
We've been making and manipulating arrays for a bit now, so here are some things to remember:

Arrays can be created from a regular Python `list` or `tuple` using the `array` function. The type of the resulting array is deduced from the type of the elements in the sequences.

# Printing Arrays
When you print an array, NumPy displays it in a similar way to nested lists, but with the following layout:
* the last axis is printed from left to right,
* the second-to-last is printed from top to bottom,
* the rest are also printed from top to bottom, with each slice separated from the next by an empty line.

>One-dimensional arrays are then printed as rows, bidimensionals as matrices and tridimensionals as lists of matrices.
>
>You might occasionally hear an array referred to as a “ndarray,” which is shorthand for “N-dimensional array.” An N-dimensional array is simply an array with any number of dimensions. You might also hear 1-D, or one-dimensional array, 2-D, or two-dimensional array, and so on. The NumPy ndarray class is used to represent both matrices and vectors. A vector is an array with a single dimension (there’s no difference between row and column vectors), while a matrix refers to an array with two dimensions. For 3-D or higher dimensional arrays, the term _`tensor`_ is also commonly used.

# Lastly MNE
## Rather than reinvent the wheel I'm borrowing heavily from MNE and Scipy Lecture Notes
### If you're needing a good reference start with these places which are rad

http://scipy-lectures.org/index.html
https://mne.tools/stable/index.html

Let's move over to the other jupytr notebook: plot_modifying_data_inplace.ipynb